/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.tecnalia.datausage.api;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.tecnalia.datausage.model.ContractStore;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-04-13T10:06:12.128Z[GMT]")
@Validated
public interface ContractAgreementApi {

    @Operation(summary = "addContractAgreement", description = "", tags={ "contract-agreement-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(schema = @Schema(implementation = String.class))),
        
        @ApiResponse(responseCode = "201", description = "Created"),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized"),
        
        @ApiResponse(responseCode = "403", description = "Forbidden"),
        
        @ApiResponse(responseCode = "404", description = "Not Found") })
    @RequestMapping(value = "/contractAgreement",
        produces = { "text/plain" }, 
        consumes = { "application/json","text/plain" }, 
        method = RequestMethod.POST)
    ResponseEntity<String> addContractAgreementUsingPOST(@Parameter(in = ParameterIn.DEFAULT, description = "Contract Agreement", required=true, schema=@Schema()) @Valid @RequestBody String body);


    @Operation(summary = "deleteContractAgreement", description = "", tags={ "contract-agreement-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(schema = @Schema(implementation = String.class))),
        
        @ApiResponse(responseCode = "204", description = "No Content"),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized"),
        
        @ApiResponse(responseCode = "403", description = "Forbidden") })
    @RequestMapping(value = "/contractAgreement/{contractUuid}",
        produces = { "text/plain" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<String> deleteContractAgreementUsingDELETE(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("contractUuid") String contractUuid);


    @Operation(summary = "getAllContractAgreements", description = "", tags={ "contract-agreement-controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(array = @ArraySchema(schema = @Schema(implementation = ContractStore.class)))),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized"),
        
        @ApiResponse(responseCode = "403", description = "Forbidden"),
        
        @ApiResponse(responseCode = "404", description = "Not Found") })
    @RequestMapping(value = "/contractAgreement",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<ContractStore>> getAllContractAgreementsGET();

}

